---
:concurrency: 20
:daemon: true
:pidfile: tmp/pids/sidekiq_push.pid
:logfile: log/sidekiq_push.log
:queues:
  - push
:schedule:
  subscriptions_scheduler:
    cron: '25 4,17 * * *'
    class: Scheduler::SubscriptionsScheduler
  media_cleanup_scheduler:
    cron: '5 4 * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '10 4 * * *'
    class: Scheduler::FeedCleanupScheduler

